#!/usr/bin/env python3
"""Generate a static web dashboard from fintech.db evaluations."""

import json
import os
import statistics
from models import get_connection

DIMENSIONS = [
    "urgency", "market_size", "pricing_potential", "acquisition_cost",
    "delivery_cost", "uniqueness", "speed_to_market", "upfront_investment",
    "upsell_potential", "evergreen_potential",
]

DIMENSION_LABELS = [d.replace("_", " ").title() for d in DIMENSIONS]

NICHE_COLORS = {
    "Payments": "#4f46e5",
    "Banking": "#2563eb",
    "Lending": "#0891b2",
    "Insurance": "#059669",
    "Wealth Management": "#d97706",
    "Crypto/Blockchain": "#7c3aed",
    "Infrastructure/API": "#475569",
    "Accounting/Tax": "#ea580c",
    "Consumer Finance": "#db2777",
    "Embedded Finance": "#0d9488",
    "Regulatory/Compliance": "#dc2626",
    "Other": "#737373",
}

OUT_DIR = os.path.join(os.path.dirname(__file__), "dashboard")


def fetch_all_data(conn):
    rows = conn.execute("""
        SELECT c.id, c.name, c.one_liner, c.long_description, c.website,
               c.status, c.batch, c.stage, c.team_size, c.subindustry,
               e.urgency, e.market_size, e.pricing_potential, e.acquisition_cost,
               e.delivery_cost, e.uniqueness, e.speed_to_market, e.upfront_investment,
               e.upsell_potential, e.evergreen_potential, e.total_score,
               e.replicability, e.niche_category, e.reasoning
        FROM evaluations e
        JOIN companies c ON e.company_id = c.id
        ORDER BY e.total_score DESC
    """).fetchall()
    return [dict(r) for r in rows]


def score_badge_class(score):
    if score >= 70:
        return "bg-emerald-100 text-emerald-800"
    elif score >= 55:
        return "bg-blue-100 text-blue-800"
    elif score >= 40:
        return "bg-amber-100 text-amber-800"
    return "bg-red-100 text-red-800"


# ── Shared HTML parts ──────────────────────────────────────────────

def nav_html(active):
    pages = [
        ("index.html", "Data Browser"),
        ("analysis.html", "Analysis"),
        ("recommendations.html", "Recommendations"),
        ("shortlist.html", "★ Shortlist"),
    ]
    links = []
    for href, label in pages:
        if label == active:
            cls = "bg-indigo-700 text-white px-4 py-2 rounded-lg text-sm font-semibold"
        else:
            cls = "text-indigo-100 hover:bg-indigo-500 px-4 py-2 rounded-lg text-sm font-medium transition"
        extra = ''
        if label == "★ Shortlist":
            extra = ' <span id="shortlist-count" class="bg-indigo-800 text-indigo-100 text-xs rounded-full px-1.5 py-0.5 ml-1"></span>'
        links.append(f'<a href="{href}" class="{cls}">{label}{extra}</a>')
    nav = f"""
    <nav class="bg-indigo-600 shadow-lg">
      <div class="w-full px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <div class="flex items-center gap-2">
            <span class="text-white font-bold text-lg tracking-tight">YC Fintech Dashboard</span>
          </div>
          <div class="flex items-center gap-1">
            {''.join(links)}
          </div>
        </div>
      </div>
    </nav>"""
    nav += """
    <script>
    (function() {
      var SL_KEY = 'yc-fintech-shortlist';
      try {
        var ids = JSON.parse(localStorage.getItem(SL_KEY) || '[]');
        var badge = document.getElementById('shortlist-count');
        if (badge) badge.textContent = ids.length > 0 ? ids.length : '';
      } catch(e) {}
    })();
    </script>"""
    return nav


HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} — YC Fintech Dashboard</title>
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect width='64' height='64' rx='14' fill='%234f46e5'/><path d='M16 44 L28 28 L38 36 L48 18' stroke='white' stroke-width='5' stroke-linecap='round' stroke-linejoin='round' fill='none'/><circle cx='48' cy='18' r='4' fill='%2334d399'/></svg>">
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  body {{ font-family: 'Inter', sans-serif; }}
</style>
</head>
<body class="bg-gray-50 min-h-screen">
"""

FOOTER = """
<footer class="text-center text-xs text-gray-400 py-8">
  Generated by YC Fintech Analysis Pipeline
</footer>
</body>
</html>"""


# ── Page 1: Data Browser ───────────────────────────────────────────

def generate_index(companies):
    niches = sorted(set(c["niche_category"] for c in companies if c["niche_category"]))
    statuses = sorted(set(c["status"] for c in companies if c["status"]))
    total = len(companies)
    avg_score = round(sum(c["total_score"] for c in companies) / total, 1) if total else 0
    top_score = max(c["total_score"] for c in companies) if total else 0
    num_niches = len(niches)

    niche_options = ''.join(f'<option value="{n}">{n}</option>' for n in niches)
    status_options = ''.join(f'<option value="{s}">{s}</option>' for s in statuses)

    # Sanitise data for JSON embedding
    safe_companies = []
    for c in companies:
        sc = {}
        for k, v in c.items():
            if isinstance(v, str):
                sc[k] = v
            elif v is None:
                sc[k] = ""
            else:
                sc[k] = v
        safe_companies.append(sc)

    data_json = json.dumps(safe_companies, ensure_ascii=False)
    dims_json = json.dumps(DIMENSIONS)
    dim_labels_json = json.dumps(DIMENSION_LABELS)
    niche_colors_json = json.dumps(NICHE_COLORS)

    html = HEAD.format(title="Data Browser")
    html += nav_html("Data Browser")
    html += f"""
<div class="w-full px-4 sm:px-6 lg:px-8 py-8">
  <!-- Hero stats -->
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
    <div class="bg-white rounded-xl shadow-sm p-5 text-center">
      <div class="text-3xl font-bold text-indigo-600">{total}</div>
      <div class="text-sm text-gray-500 mt-1">Total Companies</div>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-5 text-center">
      <div class="text-3xl font-bold text-indigo-600">{avg_score}</div>
      <div class="text-sm text-gray-500 mt-1">Avg Score</div>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-5 text-center">
      <div class="text-3xl font-bold text-indigo-600">{top_score}</div>
      <div class="text-sm text-gray-500 mt-1">Top Score</div>
    </div>
    <div class="bg-white rounded-xl shadow-sm p-5 text-center">
      <div class="text-3xl font-bold text-indigo-600">{num_niches}</div>
      <div class="text-sm text-gray-500 mt-1">Niches</div>
    </div>
  </div>

  <!-- Filter bar -->
  <div class="bg-white rounded-xl shadow-sm p-4 mb-6 flex flex-wrap items-end gap-4">
    <div class="flex-1 min-w-[200px]">
      <label class="block text-xs font-medium text-gray-500 mb-1">Search</label>
      <input id="searchInput" type="text" placeholder="Company name or keyword..."
        class="w-full border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none">
    </div>
    <div>
      <label class="block text-xs font-medium text-gray-500 mb-1">Niche</label>
      <select id="nicheSelect" class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none">
        <option value="">All Niches</option>
        {niche_options}
      </select>
    </div>
    <div>
      <label class="block text-xs font-medium text-gray-500 mb-1">Status</label>
      <select id="statusSelect" class="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-indigo-500 outline-none">
        <option value="">All</option>
        {status_options}
      </select>
    </div>
    <div>
      <label class="block text-xs font-medium text-gray-500 mb-1">Min Score: <span id="minScoreVal">0</span></label>
      <input id="minScore" type="range" min="0" max="100" value="0" class="w-32 accent-indigo-600">
    </div>
    <button onclick="resetFilters()" class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-lg text-sm font-medium transition">Reset</button>
  </div>

  <!-- Dimension Filters -->
  <div class="bg-white rounded-xl shadow-sm p-4 mb-6">
    <div class="flex items-center justify-between mb-3">
      <h3 class="text-sm font-semibold text-gray-700">Dimension Filters</h3>
      <button onclick="resetDimFilters()" class="text-xs text-indigo-600 hover:text-indigo-800 font-medium">Reset All</button>
    </div>
    <div class="grid grid-cols-2 md:grid-cols-5 gap-x-4 gap-y-3" id="dimFilters"></div>
  </div>

  <!-- Table -->
  <div class="bg-white rounded-xl shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="bg-gray-50 text-left">
          <tr>
            <th class="px-2 py-3 w-10"></th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('name')">Name <span id="sort-name" class="text-xs"></span></th>
            <th class="px-3 py-3 font-semibold text-gray-600 max-w-xs">One-liner</th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('niche_category')">Niche <span id="sort-niche_category" class="text-xs"></span></th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('total_score')">Score <span id="sort-total_score" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('urgency')" title="Urgency">Urg <span id="sort-urgency" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('market_size')" title="Market Size">Mkt <span id="sort-market_size" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('pricing_potential')" title="Pricing Potential">Price <span id="sort-pricing_potential" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('acquisition_cost')" title="Acquisition Cost">Acq <span id="sort-acquisition_cost" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('delivery_cost')" title="Delivery Cost">Del <span id="sort-delivery_cost" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('uniqueness')" title="Uniqueness">Uniq <span id="sort-uniqueness" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('speed_to_market')" title="Speed to Market">Speed <span id="sort-speed_to_market" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('upfront_investment')" title="Upfront Investment">Invest <span id="sort-upfront_investment" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('upsell_potential')" title="Upsell Potential">Upsell <span id="sort-upsell_potential" class="text-xs"></span></th>
            <th class="px-2 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap text-center text-xs" onclick="sortBy('evergreen_potential')" title="Evergreen Potential">Ever <span id="sort-evergreen_potential" class="text-xs"></span></th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('replicability')">Replic. <span id="sort-replicability" class="text-xs"></span></th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('status')">Status <span id="sort-status" class="text-xs"></span></th>
            <th class="px-3 py-3 font-semibold text-gray-600 cursor-pointer hover:text-indigo-600 whitespace-nowrap" onclick="sortBy('batch')">Batch <span id="sort-batch" class="text-xs"></span></th>
          </tr>
        </thead>
        <tbody id="tableBody"></tbody>
      </table>
    </div>
    <div id="pagination" class="flex items-center justify-between px-4 py-3 border-t border-gray-100 text-sm text-gray-500"></div>
  </div>
</div>

<!-- Expanded row modal -->
<div id="detailModal" class="hidden fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4" onclick="if(event.target===this)closeDetail()">
  <div class="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto p-6">
    <div class="flex justify-between items-start mb-4">
      <h2 id="detailName" class="text-xl font-bold text-gray-900"></h2>
      <button onclick="closeDetail()" class="text-gray-400 hover:text-gray-600 text-2xl leading-none">&times;</button>
    </div>
    <p id="detailOneLiner" class="text-gray-600 mb-2"></p>
    <div id="detailMeta" class="flex flex-wrap gap-2 mb-4"></div>
    <div id="detailDims" class="grid grid-cols-2 sm:grid-cols-5 gap-2 mb-4"></div>
    <p id="detailDesc" class="text-gray-500 text-sm mb-4"></p>
    <div class="mb-4"><canvas id="detailRadar" width="400" height="300"></canvas></div>
    <div id="detailReasoning" class="bg-gray-50 rounded-lg p-4 text-sm text-gray-700 mb-4"></div>
    <a id="detailLink" href="#" target="_blank" class="text-indigo-600 hover:underline text-sm font-medium">Visit Website &rarr;</a>
  </div>
</div>

<script>
const DATA = {data_json};
const DIMS = {dims_json};
const DIM_LABELS = {dim_labels_json};
const NICHE_COLORS = {niche_colors_json};
const PER_PAGE = 50;
let filtered = [...DATA];
let currentPage = 1;
let sortField = 'total_score';
let sortDir = -1;
let detailChart = null;

function scoreBadge(s) {{
  let cls = s >= 70 ? 'bg-emerald-100 text-emerald-800' : s >= 55 ? 'bg-blue-100 text-blue-800' : s >= 40 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800';
  return `<span class="${{cls}} px-2 py-0.5 rounded-full text-xs font-semibold">${{s}}</span>`;
}}

function dimBadge(v) {{
  let cls = v >= 8 ? 'bg-emerald-100 text-emerald-800' : v >= 6 ? 'bg-blue-100 text-blue-800' : v >= 4 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800';
  return `<span class="${{cls}} inline-block w-7 text-center py-0.5 rounded text-xs font-semibold">${{v}}</span>`;
}}

function applyFilters() {{
  const q = document.getElementById('searchInput').value.toLowerCase();
  const niche = document.getElementById('nicheSelect').value;
  const status = document.getElementById('statusSelect').value;
  const minScore = parseInt(document.getElementById('minScore').value);
  document.getElementById('minScoreVal').textContent = minScore;
  const dimMins = {{}};
  DIMS.forEach(d => {{ dimMins[d] = parseInt(document.getElementById('dim-' + d).value); document.getElementById('dimval-' + d).textContent = dimMins[d]; }});
  filtered = DATA.filter(c => {{
    if (q && !c.name.toLowerCase().includes(q) && !(c.one_liner||'').toLowerCase().includes(q)) return false;
    if (niche && c.niche_category !== niche) return false;
    if (status && c.status !== status) return false;
    if (c.total_score < minScore) return false;
    for (const d of DIMS) {{ if (dimMins[d] > 0 && c[d] < dimMins[d]) return false; }}
    return true;
  }});
  doSort();
  currentPage = 1;
  render();
}}

function doSort() {{
  filtered.sort((a, b) => {{
    let va = a[sortField] ?? '', vb = b[sortField] ?? '';
    if (typeof va === 'string') va = va.toLowerCase();
    if (typeof vb === 'string') vb = vb.toLowerCase();
    return va < vb ? -sortDir : va > vb ? sortDir : 0;
  }});
}}

function sortBy(field) {{
  if (sortField === field) sortDir *= -1;
  else {{ sortField = field; sortDir = field === 'name' || field === 'niche_category' || field === 'status' || field === 'batch' ? 1 : -1; }}
  document.querySelectorAll('[id^=sort-]').forEach(e => e.textContent = '');
  const el = document.getElementById('sort-' + field);
  if (el) el.textContent = sortDir === 1 ? '▲' : '▼';
  doSort();
  render();
}}

function render() {{
  const start = (currentPage - 1) * PER_PAGE;
  const page = filtered.slice(start, start + PER_PAGE);
  const tbody = document.getElementById('tableBody');
  tbody.innerHTML = page.map((c, i) => `
    <tr class="border-t border-gray-100 hover:bg-indigo-50/40 cursor-pointer transition" onclick="showDetail(${{start + i}})">
      <td class="px-2 py-3 text-center"><button onclick="event.stopPropagation();toggleStar(${{c.id}})" class="text-lg leading-none hover:scale-125 transition-transform ${{isStarred(c.id) ? 'text-yellow-500' : 'text-gray-300'}}" title="Toggle shortlist">${{isStarred(c.id) ? '★' : '☆'}}</button></td>
      <td class="px-3 py-3 font-medium text-gray-900 whitespace-nowrap">${{c.name}}</td>
      <td class="px-3 py-3 text-gray-600 max-w-xs truncate">${{c.one_liner || ''}}</td>
      <td class="px-3 py-3"><span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium" style="background:${{NICHE_COLORS[c.niche_category] || '#737373'}}20;color:${{NICHE_COLORS[c.niche_category] || '#737373'}}">${{c.niche_category}}</span></td>
      <td class="px-3 py-3">${{scoreBadge(c.total_score)}}</td>
      ${{DIMS.map(d => `<td class="px-2 py-3 text-center">${{dimBadge(c[d])}}</td>`).join('')}}
      <td class="px-3 py-3 text-gray-700">${{c.replicability}}/10</td>
      <td class="px-3 py-3"><span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium ${{c.status==='Active'?'bg-emerald-100 text-emerald-700':'bg-gray-100 text-gray-600'}}">${{c.status||''}}</span></td>
      <td class="px-3 py-3 text-gray-500">${{c.batch || ''}}</td>
    </tr>
  `).join('');

  const totalPages = Math.ceil(filtered.length / PER_PAGE);
  document.getElementById('pagination').innerHTML = `
    <span>Showing ${{filtered.length ? start+1 : 0}}-${{Math.min(start+PER_PAGE, filtered.length)}} of ${{filtered.length}} companies</span>
    <div class="flex gap-1">
      <button onclick="goPage(${{currentPage-1}})" ${{currentPage<=1?'disabled':''}} class="px-3 py-1 rounded border border-gray-300 hover:bg-gray-100 disabled:opacity-40 disabled:cursor-not-allowed">Prev</button>
      <span class="px-3 py-1 text-gray-600">Page ${{currentPage}} / ${{totalPages}}</span>
      <button onclick="goPage(${{currentPage+1}})" ${{currentPage>=totalPages?'disabled':''}} class="px-3 py-1 rounded border border-gray-300 hover:bg-gray-100 disabled:opacity-40 disabled:cursor-not-allowed">Next</button>
    </div>
  `;
}}

function goPage(p) {{ currentPage = p; render(); window.scrollTo(0, 300); }}

function resetDimFilters() {{
  DIMS.forEach(d => {{ document.getElementById('dim-' + d).value = 0; }});
  applyFilters();
}}

function resetFilters() {{
  document.getElementById('searchInput').value = '';
  document.getElementById('nicheSelect').value = '';
  document.getElementById('statusSelect').value = '';
  document.getElementById('minScore').value = 0;
  resetDimFilters();
}}

function showDetail(idx) {{
  const c = filtered[idx];
  document.getElementById('detailName').textContent = c.name;
  document.getElementById('detailOneLiner').textContent = c.one_liner || '';
  document.getElementById('detailMeta').innerHTML = `
    ${{scoreBadge(c.total_score)}}
    <span class="px-2 py-0.5 rounded-full text-xs font-medium" style="background:${{NICHE_COLORS[c.niche_category]||'#737373'}}20;color:${{NICHE_COLORS[c.niche_category]||'#737373'}}">${{c.niche_category}}</span>
    <span class="bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full text-xs">Replicability: ${{c.replicability}}/10</span>
    <span class="bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full text-xs">${{c.status}}</span>
    ${{c.batch ? `<span class="bg-gray-100 text-gray-600 px-2 py-0.5 rounded-full text-xs">${{c.batch}}</span>` : ''}}
  `;
  document.getElementById('detailDims').innerHTML = DIMS.map((d, i) =>
    `<div class="flex items-center justify-between bg-gray-50 rounded-lg px-3 py-1.5">
      <span class="text-xs text-gray-600">${{DIM_LABELS[i]}}</span>
      ${{dimBadge(c[d])}}
    </div>`
  ).join('');
  document.getElementById('detailDesc').textContent = c.long_description || '';
  document.getElementById('detailReasoning').innerHTML = '<strong class="text-gray-900">Analysis:</strong> ' + (c.reasoning || '');
  const link = document.getElementById('detailLink');
  if (c.website) {{ link.href = c.website; link.classList.remove('hidden'); }}
  else {{ link.classList.add('hidden'); }}

  if (detailChart) detailChart.destroy();
  const ctx = document.getElementById('detailRadar').getContext('2d');
  detailChart = new Chart(ctx, {{
    type: 'radar',
    data: {{
      labels: DIM_LABELS,
      datasets: [{{ label: c.name, data: DIMS.map(d => c[d]), backgroundColor: 'rgba(79,70,229,0.15)', borderColor: '#4f46e5', pointBackgroundColor: '#4f46e5', pointRadius: 3 }}]
    }},
    options: {{ scales: {{ r: {{ min: 0, max: 10, ticks: {{ stepSize: 2 }} }} }}, plugins: {{ legend: {{ display: false }} }} }}
  }});
  document.getElementById('detailModal').classList.remove('hidden');
}}

function closeDetail() {{ document.getElementById('detailModal').classList.add('hidden'); }}

// Build dimension filter sliders
const dimContainer = document.getElementById('dimFilters');
DIMS.forEach((d, i) => {{
  const div = document.createElement('div');
  div.innerHTML = `
    <label class="block text-xs font-medium text-gray-500 mb-1">${{DIM_LABELS[i]}}: <span id="dimval-${{d}}" class="font-semibold text-gray-700">0</span></label>
    <input id="dim-${{d}}" type="range" min="0" max="10" value="0" class="w-full accent-indigo-600 h-1.5">
  `;
  dimContainer.appendChild(div);
  div.querySelector('input').addEventListener('input', applyFilters);
}});

document.getElementById('searchInput').addEventListener('input', applyFilters);
document.getElementById('nicheSelect').addEventListener('change', applyFilters);
document.getElementById('statusSelect').addEventListener('change', applyFilters);
document.getElementById('minScore').addEventListener('input', applyFilters);
document.addEventListener('keydown', e => {{ if (e.key === 'Escape') closeDetail(); }});

// ── Shortlist (localStorage) ──
const SL_KEY = 'yc-fintech-shortlist';
function getShortlist() {{ try {{ return JSON.parse(localStorage.getItem(SL_KEY) || '[]'); }} catch(e) {{ return []; }} }}
function saveShortlist(ids) {{ localStorage.setItem(SL_KEY, JSON.stringify(ids)); }}
function isStarred(id) {{ return getShortlist().includes(id); }}
function toggleStar(id) {{
  let ids = getShortlist();
  if (ids.includes(id)) ids = ids.filter(x => x !== id);
  else ids.push(id);
  saveShortlist(ids);
  render();
  const badge = document.getElementById('shortlist-count');
  if (badge) badge.textContent = ids.length > 0 ? ids.length : '';
}}

// Initial
sortBy('total_score');
</script>
"""
    html += FOOTER
    return html


# ── Page 2: Analysis ───────────────────────────────────────────────

def compute_analysis_data(companies):
    top20 = companies[:20]

    # Score distribution
    buckets = {"Excellent (70+)": 0, "Strong (55-69)": 0, "Average (40-54)": 0, "Weak (<40)": 0}
    for c in companies:
        s = c["total_score"]
        if s >= 70: buckets["Excellent (70+)"] += 1
        elif s >= 55: buckets["Strong (55-69)"] += 1
        elif s >= 40: buckets["Average (40-54)"] += 1
        else: buckets["Weak (<40)"] += 1

    # Best niches
    niche_data = {}
    for c in companies:
        n = c["niche_category"]
        if n not in niche_data:
            niche_data[n] = {"scores": [], "dims": {d: [] for d in DIMENSIONS}}
        niche_data[n]["scores"].append(c["total_score"])
        for d in DIMENSIONS:
            niche_data[n]["dims"][d].append(c[d])

    niche_stats = []
    for n, nd in niche_data.items():
        niche_stats.append({
            "niche": n,
            "count": len(nd["scores"]),
            "avg_score": round(sum(nd["scores"]) / len(nd["scores"]), 1),
            "dim_avgs": {d: round(sum(nd["dims"][d]) / len(nd["dims"][d]), 1) for d in DIMENSIONS},
        })
    niche_stats.sort(key=lambda x: x["avg_score"], reverse=True)

    # Global dimension averages
    global_dims = {d: round(sum(c[d] for c in companies) / len(companies), 1) for d in DIMENSIONS}

    # Active vs Inactive
    status_data = {}
    for c in companies:
        st = c["status"] or "Unknown"
        if st not in status_data:
            status_data[st] = {"count": 0, "scores": []}
        status_data[st]["count"] += 1
        status_data[st]["scores"].append(c["total_score"])
    status_stats = [{"status": k, "count": v["count"], "avg_score": round(sum(v["scores"]) / len(v["scores"]), 1)} for k, v in status_data.items()]
    status_stats.sort(key=lambda x: x["avg_score"], reverse=True)

    return {
        "top20": [{"name": c["name"], "score": c["total_score"], "niche": c["niche_category"]} for c in top20],
        "buckets": buckets,
        "niche_stats": niche_stats,
        "global_dims": global_dims,
        "status_stats": status_stats,
    }


def generate_analysis(companies):
    ad = compute_analysis_data(companies)
    data_json = json.dumps(ad, ensure_ascii=False)
    dim_labels_json = json.dumps(DIMENSION_LABELS)
    dims_json = json.dumps(DIMENSIONS)
    niche_colors_json = json.dumps(NICHE_COLORS)

    html = HEAD.format(title="Analysis")
    html += nav_html("Analysis")
    html += f"""
<div class="w-full px-4 sm:px-6 lg:px-8 py-8">
  <h1 class="text-2xl font-bold text-gray-900 mb-6">Visual Analysis</h1>
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">

    <!-- Top 20 Companies -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Top 20 Companies</h3>
      <canvas id="top20Chart" height="400"></canvas>
    </div>

    <!-- Score Distribution -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Score Distribution</h3>
      <canvas id="distChart" height="400"></canvas>
    </div>

    <!-- Best Niches -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Best Niches by Avg Score</h3>
      <canvas id="nicheChart" height="400"></canvas>
    </div>

    <!-- Dimension Averages -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Dimension Averages (Global)</h3>
      <canvas id="dimChart" height="400"></canvas>
    </div>

    <!-- Niche Dimension Profiles -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Niche Dimension Profiles</h3>
      <select id="nicheProfileSelect" class="border border-gray-300 rounded-lg px-3 py-2 text-sm mb-4 focus:ring-2 focus:ring-indigo-500 outline-none"></select>
      <canvas id="nicheProfileChart" height="350"></canvas>
    </div>

    <!-- Active vs Inactive -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <h3 class="text-lg font-semibold text-gray-900 mb-4">Active vs Inactive</h3>
      <canvas id="statusChart" height="400"></canvas>
    </div>

  </div>
</div>

<script>
const AD = {data_json};
const DIM_LABELS = {dim_labels_json};
const DIMS = {dims_json};
const NICHE_COLORS = {niche_colors_json};

Chart.register(ChartDataLabels);
Chart.defaults.set('plugins.datalabels', {{ display: false }});

// 1. Top 20 horizontal bar
new Chart(document.getElementById('top20Chart'), {{
  type: 'bar',
  data: {{
    labels: AD.top20.map(c => c.name),
    datasets: [{{
      data: AD.top20.map(c => c.score),
      backgroundColor: AD.top20.map(c => (NICHE_COLORS[c.niche] || '#737373') + 'cc'),
      borderRadius: 4,
    }}]
  }},
  options: {{
    indexAxis: 'y',
    plugins: {{ legend: {{ display: false }}, datalabels: {{ display: true, anchor: 'end', align: 'end', font: {{ size: 11, weight: 600 }}, color: '#374151' }} }},
    scales: {{ x: {{ beginAtZero: true, max: 100 }} }},
  }}
}});

// 2. Score Distribution donut
new Chart(document.getElementById('distChart'), {{
  type: 'doughnut',
  data: {{
    labels: Object.keys(AD.buckets),
    datasets: [{{
      data: Object.values(AD.buckets),
      backgroundColor: ['#059669', '#2563eb', '#d97706', '#dc2626'],
      borderWidth: 0,
    }}]
  }},
  options: {{
    plugins: {{
      datalabels: {{ display: true, color: '#fff', font: {{ weight: 'bold', size: 14 }}, formatter: v => v }},
      legend: {{ position: 'bottom' }}
    }},
    cutout: '55%',
  }}
}});

// 3. Best Niches bar
new Chart(document.getElementById('nicheChart'), {{
  type: 'bar',
  data: {{
    labels: AD.niche_stats.map(n => n.niche),
    datasets: [{{
      label: 'Avg Score',
      data: AD.niche_stats.map(n => n.avg_score),
      backgroundColor: AD.niche_stats.map(n => (NICHE_COLORS[n.niche] || '#737373') + 'cc'),
      borderRadius: 4,
    }}]
  }},
  options: {{
    plugins: {{
      legend: {{ display: false }},
      datalabels: {{ display: true, anchor: 'end', align: 'end', font: {{ size: 10 }}, color: '#6b7280',
        formatter: (v, ctx) => v + ' (n=' + AD.niche_stats[ctx.dataIndex].count + ')'
      }}
    }},
    scales: {{ y: {{ beginAtZero: true, max: 100 }}, x: {{ ticks: {{ maxRotation: 45, minRotation: 45 }} }} }},
  }}
}});

// 4. Dimension Averages radar
new Chart(document.getElementById('dimChart'), {{
  type: 'radar',
  data: {{
    labels: DIM_LABELS,
    datasets: [{{
      label: 'Global Average',
      data: DIMS.map(d => AD.global_dims[d]),
      backgroundColor: 'rgba(79,70,229,0.15)',
      borderColor: '#4f46e5',
      pointBackgroundColor: '#4f46e5',
      pointRadius: 4,
    }}]
  }},
  options: {{ scales: {{ r: {{ min: 0, max: 10, ticks: {{ stepSize: 2 }} }} }}, plugins: {{ datalabels: {{ display: false }} }} }}
}});

// 5. Niche Dimension Profiles
const npSelect = document.getElementById('nicheProfileSelect');
AD.niche_stats.forEach(n => {{
  const opt = document.createElement('option');
  opt.value = n.niche;
  opt.textContent = n.niche;
  npSelect.appendChild(opt);
}});
let npChart = null;
function renderNicheProfile() {{
  const niche = npSelect.value;
  const ns = AD.niche_stats.find(n => n.niche === niche);
  if (!ns) return;
  if (npChart) npChart.destroy();
  npChart = new Chart(document.getElementById('nicheProfileChart'), {{
    type: 'radar',
    data: {{
      labels: DIM_LABELS,
      datasets: [
        {{ label: niche, data: DIMS.map(d => ns.dim_avgs[d]), backgroundColor: (NICHE_COLORS[niche]||'#737373') + '25', borderColor: NICHE_COLORS[niche]||'#737373', pointBackgroundColor: NICHE_COLORS[niche]||'#737373', pointRadius: 4 }},
        {{ label: 'Global Avg', data: DIMS.map(d => AD.global_dims[d]), backgroundColor: 'rgba(156,163,175,0.1)', borderColor: '#9ca3af', borderDash: [5,5], pointRadius: 2 }},
      ]
    }},
    options: {{ scales: {{ r: {{ min: 0, max: 10, ticks: {{ stepSize: 2 }} }} }}, plugins: {{ datalabels: {{ display: false }} }} }}
  }});
}}
npSelect.addEventListener('change', renderNicheProfile);
renderNicheProfile();

// 6. Active vs Inactive grouped bar
new Chart(document.getElementById('statusChart'), {{
  type: 'bar',
  data: {{
    labels: AD.status_stats.map(s => s.status),
    datasets: [
      {{ label: 'Count', data: AD.status_stats.map(s => s.count), backgroundColor: '#4f46e5cc', borderRadius: 4, yAxisID: 'y' }},
      {{ label: 'Avg Score', data: AD.status_stats.map(s => s.avg_score), backgroundColor: '#059669cc', borderRadius: 4, yAxisID: 'y1' }},
    ]
  }},
  options: {{
    plugins: {{
      datalabels: {{ display: true, anchor: 'end', align: 'end', font: {{ size: 11, weight: 600 }}, color: '#374151' }}
    }},
    scales: {{
      y: {{ type: 'linear', position: 'left', title: {{ display: true, text: 'Count' }} }},
      y1: {{ type: 'linear', position: 'right', title: {{ display: true, text: 'Avg Score' }}, grid: {{ drawOnChartArea: false }} }},
    }}
  }}
}});
</script>
"""
    html += FOOTER
    return html


# ── Page 3: Recommendations ───────────────────────────────────────

def compute_recommendations(companies):
    # Most replicable (replicability >= 7, top 20 by score)
    replicable = sorted(
        [c for c in companies if c["replicability"] >= 7],
        key=lambda c: c["total_score"], reverse=True
    )[:20]

    # Niche opportunity scores
    niche_data = {}
    for c in companies:
        n = c["niche_category"]
        if n not in niche_data:
            niche_data[n] = {"scores": [], "replicabilities": [], "dims": {d: [] for d in DIMENSIONS}}
        niche_data[n]["scores"].append(c["total_score"])
        niche_data[n]["replicabilities"].append(c["replicability"])
        for d in DIMENSIONS:
            niche_data[n]["dims"][d].append(c[d])

    niche_opp = []
    for n, nd in niche_data.items():
        avg_score = sum(nd["scores"]) / len(nd["scores"])
        avg_replic = sum(nd["replicabilities"]) / len(nd["replicabilities"])
        opp_score = round(avg_score * 0.5 + avg_replic * 3 + max(0, 10 - len(nd["scores"]) * 0.3) * 2, 1)
        niche_opp.append({
            "niche": n, "count": len(nd["scores"]),
            "avg_score": round(avg_score, 1),
            "avg_replic": round(avg_replic, 1),
            "opp_score": opp_score,
        })
    niche_opp.sort(key=lambda x: x["opp_score"], reverse=True)

    # Strategic insights
    all_scores = [c["total_score"] for c in companies]

    # Highest-scoring dimension
    dim_avgs = {d: sum(c[d] for c in companies) / len(companies) for d in DIMENSIONS}
    best_dim = max(dim_avgs, key=dim_avgs.get)

    # Most variance dimension
    dim_vars = {d: statistics.stdev(c[d] for c in companies) for d in DIMENSIONS}
    most_var_dim = max(dim_vars, key=dim_vars.get)

    # Sweet spot companies
    sweet_spot = [c for c in companies if c["total_score"] >= 65 and c["replicability"] >= 6]

    # Underserved niche
    avg_global = sum(all_scores) / len(all_scores)
    above_avg_niches = [no for no in niche_opp if no["avg_score"] >= avg_global]
    underserved = min(above_avg_niches, key=lambda x: x["count"]) if above_avg_niches else None

    # Active vs Dead
    active = [c for c in companies if c["status"] == "Active"]
    inactive = [c for c in companies if c["status"] != "Active"]
    active_avg = round(sum(c["total_score"] for c in active) / len(active), 1) if active else 0
    inactive_avg = round(sum(c["total_score"] for c in inactive) / len(inactive), 1) if inactive else 0

    # Quick wins
    quick_wins = [c for c in companies if c["speed_to_market"] >= 8 and c["upfront_investment"] >= 8]
    quick_wins.sort(key=lambda c: c["total_score"], reverse=True)

    return {
        "replicable": [{
            "name": c["name"], "one_liner": c["one_liner"] or "", "score": c["total_score"],
            "replicability": c["replicability"], "niche": c["niche_category"], "reasoning": c["reasoning"] or "",
        } for c in replicable],
        "niche_opp": niche_opp,
        "insights": {
            "best_dim": {"dim": best_dim.replace("_", " ").title(), "avg": round(dim_avgs[best_dim], 1)},
            "most_var_dim": {"dim": most_var_dim.replace("_", " ").title(), "stdev": round(dim_vars[most_var_dim], 2)},
            "sweet_spot_count": len(sweet_spot),
            "underserved": underserved,
            "active_avg": active_avg,
            "inactive_avg": inactive_avg,
            "active_count": len(active),
            "inactive_count": len(inactive),
            "quick_wins_count": len(quick_wins),
            "quick_wins_top3": [{"name": c["name"], "score": c["total_score"]} for c in quick_wins[:3]],
        }
    }


def generate_recommendations(companies):
    rec = compute_recommendations(companies)
    niche_colors_json = json.dumps(NICHE_COLORS)

    # Build replicable cards
    rep_cards = ""
    for c in rec["replicable"]:
        badge_cls = score_badge_class(c["score"])
        color = NICHE_COLORS.get(c["niche"], "#737373")
        rep_cards += f"""
        <div class="bg-white rounded-xl shadow-sm p-5 flex flex-col">
          <div class="flex items-start justify-between mb-2">
            <h4 class="font-semibold text-gray-900">{c["name"]}</h4>
            <span class="{badge_cls} px-2 py-0.5 rounded-full text-xs font-semibold ml-2 whitespace-nowrap">{c["score"]}</span>
          </div>
          <p class="text-sm text-gray-600 mb-3 flex-1">{c["one_liner"]}</p>
          <div class="flex items-center gap-2 mb-2">
            <span class="px-2 py-0.5 rounded-full text-xs font-medium" style="background:{color}20;color:{color}">{c["niche"]}</span>
            <span class="bg-purple-100 text-purple-700 px-2 py-0.5 rounded-full text-xs font-medium">Replic: {c["replicability"]}/10</span>
          </div>
          <details class="text-xs text-gray-500">
            <summary class="cursor-pointer text-indigo-600 font-medium">Analysis</summary>
            <p class="mt-1">{c["reasoning"][:300]}{'...' if len(c["reasoning"]) > 300 else ''}</p>
          </details>
        </div>"""

    # Niche opportunity data
    niche_opp_json = json.dumps(rec["niche_opp"], ensure_ascii=False)

    # Top 5 niche summary cards
    top5_cards = ""
    for no in rec["niche_opp"][:5]:
        color = NICHE_COLORS.get(no["niche"], "#737373")
        top5_cards += f"""
        <div class="bg-white rounded-xl shadow-sm p-5 border-l-4" style="border-color:{color}">
          <h4 class="font-semibold text-gray-900 mb-1">{no["niche"]}</h4>
          <div class="grid grid-cols-3 gap-2 text-center text-sm">
            <div><div class="font-bold text-indigo-600">{no["opp_score"]}</div><div class="text-xs text-gray-500">Opp. Score</div></div>
            <div><div class="font-bold text-gray-800">{no["avg_score"]}</div><div class="text-xs text-gray-500">Avg Score</div></div>
            <div><div class="font-bold text-gray-800">{no["count"]}</div><div class="text-xs text-gray-500">Companies</div></div>
          </div>
        </div>"""

    ins = rec["insights"]

    html = HEAD.format(title="Recommendations")
    html += nav_html("Recommendations")
    html += f"""
<div class="w-full px-4 sm:px-6 lg:px-8 py-8">

  <!-- Most Replicable -->
  <div class="mb-10">
    <h2 class="text-2xl font-bold text-gray-900 mb-1">Most Replicable Ideas</h2>
    <p class="text-gray-500 mb-6">Top-scoring companies with replicability &ge; 7</p>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {rep_cards}
    </div>
  </div>

  <!-- Best Niches to Enter -->
  <div class="mb-10">
    <h2 class="text-2xl font-bold text-gray-900 mb-1">Best Niches to Enter</h2>
    <p class="text-gray-500 mb-6">Composite opportunity score (avg quality + replicability + market gap)</p>
    <div class="bg-white rounded-xl shadow-sm p-6 mb-6">
      <canvas id="nicheOppChart" height="300"></canvas>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
      {top5_cards}
    </div>
  </div>

  <!-- Strategic Takeaways -->
  <div class="mb-10">
    <h2 class="text-2xl font-bold text-gray-900 mb-6">Strategic Takeaways</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-indigo-600 font-bold text-2xl mb-1">{ins["best_dim"]["avg"]}/10</div>
        <h4 class="font-semibold text-gray-900 mb-1">Strongest Dimension</h4>
        <p class="text-sm text-gray-600"><strong>{ins["best_dim"]["dim"]}</strong> scores highest on average across all companies, signaling a shared market strength.</p>
      </div>

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-amber-600 font-bold text-2xl mb-1">&sigma; {ins["most_var_dim"]["stdev"]}</div>
        <h4 class="font-semibold text-gray-900 mb-1">Highest Variance</h4>
        <p class="text-sm text-gray-600"><strong>{ins["most_var_dim"]["dim"]}</strong> has the most spread — a differentiation opportunity where the right strategy matters.</p>
      </div>

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-emerald-600 font-bold text-2xl mb-1">{ins["sweet_spot_count"]}</div>
        <h4 class="font-semibold text-gray-900 mb-1">Sweet Spot Companies</h4>
        <p class="text-sm text-gray-600">Companies scoring &ge; 65 with replicability &ge; 6. High quality <em>and</em> feasible to replicate.</p>
      </div>

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-violet-600 font-bold text-2xl mb-1">{ins["underserved"]["niche"] if ins["underserved"] else "N/A"}</div>
        <h4 class="font-semibold text-gray-900 mb-1">Underserved Niche</h4>
        <p class="text-sm text-gray-600">Fewest companies among above-average niches{f" (only {ins['underserved']['count']} companies, avg {ins['underserved']['avg_score']})" if ins["underserved"] else ""}. Less crowded, strong signal.</p>
      </div>

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-blue-600 font-bold text-2xl mb-1">{ins["active_avg"]} vs {ins["inactive_avg"]}</div>
        <h4 class="font-semibold text-gray-900 mb-1">Active vs Dead Signal</h4>
        <p class="text-sm text-gray-600">{ins["active_count"]} active companies avg {ins["active_avg"]} vs {ins["inactive_count"]} inactive at {ins["inactive_avg"]}. {"Higher-scoring ideas tend to survive." if ins["active_avg"] > ins["inactive_avg"] else "Score alone does not predict survival."}</p>
      </div>

      <div class="bg-white rounded-xl shadow-sm p-5">
        <div class="text-orange-600 font-bold text-2xl mb-1">{ins["quick_wins_count"]}</div>
        <h4 class="font-semibold text-gray-900 mb-1">Quick Wins</h4>
        <p class="text-sm text-gray-600">Companies with speed_to_market &ge; 8 AND upfront_investment &ge; 8. Fast to build, cheap to start.{" Top: " + ", ".join(qw["name"] for qw in ins["quick_wins_top3"]) + "." if ins["quick_wins_top3"] else ""}</p>
      </div>

    </div>
  </div>

</div>

<script>
const NICHE_COLORS = {niche_colors_json};
const NICHE_OPP = {niche_opp_json};

Chart.register(ChartDataLabels);
Chart.defaults.set('plugins.datalabels', {{ display: false }});

new Chart(document.getElementById('nicheOppChart'), {{
  type: 'bar',
  data: {{
    labels: NICHE_OPP.map(n => n.niche),
    datasets: [{{
      label: 'Opportunity Score',
      data: NICHE_OPP.map(n => n.opp_score),
      backgroundColor: NICHE_OPP.map(n => (NICHE_COLORS[n.niche] || '#737373') + 'cc'),
      borderRadius: 4,
    }}]
  }},
  options: {{
    plugins: {{
      legend: {{ display: false }},
      datalabels: {{ display: true, anchor: 'end', align: 'end', font: {{ size: 11, weight: 600 }}, color: '#374151' }}
    }},
    scales: {{ y: {{ beginAtZero: true }}, x: {{ ticks: {{ maxRotation: 45, minRotation: 45 }} }} }},
  }}
}});
</script>
"""
    html += FOOTER
    return html


# ── Page 4: Shortlist & Compare ────────────────────────────────────

def generate_shortlist(companies):
    # Sanitise data for JSON embedding (same as index)
    safe_companies = []
    for c in companies:
        sc = {}
        for k, v in c.items():
            if isinstance(v, str):
                sc[k] = v
            elif v is None:
                sc[k] = ""
            else:
                sc[k] = v
        safe_companies.append(sc)

    data_json = json.dumps(safe_companies, ensure_ascii=False)
    dims_json = json.dumps(DIMENSIONS)
    dim_labels_json = json.dumps(DIMENSION_LABELS)
    niche_colors_json = json.dumps(NICHE_COLORS)

    html = HEAD.format(title="Shortlist")
    html += nav_html("★ Shortlist")
    html += f"""
<div class="w-full px-4 sm:px-6 lg:px-8 py-8">
  <h1 class="text-2xl font-bold text-gray-900 mb-2">Your Shortlist</h1>
  <p class="text-gray-500 mb-6">Star companies from the <a href="index.html" class="text-indigo-600 hover:underline">Data Browser</a> to add them here.</p>

  <!-- Empty state -->
  <div id="emptyState" class="hidden bg-white rounded-xl shadow-sm p-12 text-center mb-6">
    <div class="text-5xl mb-4">☆</div>
    <h3 class="text-lg font-semibold text-gray-700 mb-2">No companies starred yet</h3>
    <p class="text-gray-500 mb-4">Go to the <a href="index.html" class="text-indigo-600 hover:underline font-medium">Data Browser</a> and click the star icon to add companies.</p>
  </div>

  <!-- Action bar -->
  <div id="actionBar" class="hidden bg-white rounded-xl shadow-sm p-4 mb-4 flex flex-wrap items-center gap-3">
    <button onclick="selectAll()" class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-3 py-1.5 rounded-lg text-sm font-medium transition">Select All</button>
    <button onclick="deselectAll()" class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-3 py-1.5 rounded-lg text-sm font-medium transition">Deselect All</button>
    <button id="compareBtn" onclick="compareSelected()" disabled class="bg-indigo-600 hover:bg-indigo-700 disabled:bg-gray-300 disabled:cursor-not-allowed text-white px-4 py-1.5 rounded-lg text-sm font-semibold transition">Compare Selected (0)</button>
  </div>

  <!-- Shortlist table -->
  <div id="shortlistTable" class="hidden bg-white rounded-xl shadow-sm overflow-hidden mb-6">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead class="bg-gray-50 text-left">
          <tr>
            <th class="px-2 py-3 w-10"><input type="checkbox" id="checkAll" onchange="toggleCheckAll(this.checked)" class="accent-indigo-600"></th>
            <th class="px-2 py-3 w-10"></th>
            <th class="px-3 py-3 font-semibold text-gray-600 whitespace-nowrap">Name</th>
            <th class="px-3 py-3 font-semibold text-gray-600 max-w-xs">One-liner</th>
            <th class="px-3 py-3 font-semibold text-gray-600 whitespace-nowrap">Niche</th>
            <th class="px-3 py-3 font-semibold text-gray-600 whitespace-nowrap">Score</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Urgency">Urg</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Market Size">Mkt</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Pricing Potential">Price</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Acquisition Cost">Acq</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Delivery Cost">Del</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Uniqueness">Uniq</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Speed to Market">Speed</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Upfront Investment">Invest</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Upsell Potential">Upsell</th>
            <th class="px-2 py-3 font-semibold text-gray-600 text-center text-xs whitespace-nowrap" title="Evergreen Potential">Ever</th>
          </tr>
        </thead>
        <tbody id="slBody"></tbody>
      </table>
    </div>
  </div>

  <!-- Comparison section -->
  <div id="compSection" class="hidden mb-6">
    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-bold text-gray-900">Comparison</h2>
      <button onclick="closeComparison()" class="bg-gray-100 hover:bg-gray-200 text-gray-700 px-3 py-1.5 rounded-lg text-sm font-medium transition">Close Comparison</button>
    </div>

    <!-- Side-by-side dimension table -->
    <div class="bg-white rounded-xl shadow-sm overflow-hidden mb-6">
      <div class="overflow-x-auto">
        <table class="w-full text-sm" id="compTable"></table>
      </div>
    </div>

    <!-- Radar chart -->
    <div class="bg-white rounded-xl shadow-sm p-6">
      <canvas id="compRadar" height="400"></canvas>
    </div>
  </div>
</div>

<script>
const DATA = {data_json};
const DIMS = {dims_json};
const DIM_LABELS = {dim_labels_json};
const NICHE_COLORS = {niche_colors_json};
const SL_KEY = 'yc-fintech-shortlist';
const COMP_COLORS = ['#4f46e5','#059669','#dc2626','#d97706','#7c3aed','#db2777','#0891b2','#ea580c','#0d9488','#2563eb','#475569','#737373'];
let selectedIds = new Set();
let compChart = null;

function getShortlist() {{ try {{ return JSON.parse(localStorage.getItem(SL_KEY) || '[]'); }} catch(e) {{ return []; }} }}
function saveShortlist(ids) {{ localStorage.setItem(SL_KEY, JSON.stringify(ids)); }}

function scoreBadge(s) {{
  let cls = s >= 70 ? 'bg-emerald-100 text-emerald-800' : s >= 55 ? 'bg-blue-100 text-blue-800' : s >= 40 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800';
  return `<span class="${{cls}} px-2 py-0.5 rounded-full text-xs font-semibold">${{s}}</span>`;
}}

function dimBadge(v) {{
  let cls = v >= 8 ? 'bg-emerald-100 text-emerald-800' : v >= 6 ? 'bg-blue-100 text-blue-800' : v >= 4 ? 'bg-amber-100 text-amber-800' : 'bg-red-100 text-red-800';
  return `<span class="${{cls}} inline-block w-7 text-center py-0.5 rounded text-xs font-semibold">${{v}}</span>`;
}}

function updateBadge() {{
  const ids = getShortlist();
  const badge = document.getElementById('shortlist-count');
  if (badge) badge.textContent = ids.length > 0 ? ids.length : '';
}}

function updateCompareBtn() {{
  const btn = document.getElementById('compareBtn');
  btn.textContent = `Compare Selected (${{selectedIds.size}})`;
  btn.disabled = selectedIds.size < 2;
}}

function renderShortlist() {{
  const ids = getShortlist();
  const starred = DATA.filter(c => ids.includes(c.id));

  if (starred.length === 0) {{
    document.getElementById('emptyState').classList.remove('hidden');
    document.getElementById('actionBar').classList.add('hidden');
    document.getElementById('shortlistTable').classList.add('hidden');
    document.getElementById('compSection').classList.add('hidden');
    return;
  }}

  document.getElementById('emptyState').classList.add('hidden');
  document.getElementById('actionBar').classList.remove('hidden');
  document.getElementById('shortlistTable').classList.remove('hidden');

  const tbody = document.getElementById('slBody');
  tbody.innerHTML = starred.map(c => `
    <tr class="border-t border-gray-100 hover:bg-indigo-50/40 transition">
      <td class="px-2 py-3 text-center"><input type="checkbox" ${{selectedIds.has(c.id)?'checked':''}} onchange="toggleSelect(${{c.id}},this.checked)" class="accent-indigo-600"></td>
      <td class="px-2 py-3 text-center"><button onclick="unstar(${{c.id}})" class="text-lg leading-none text-yellow-500 hover:scale-125 transition-transform" title="Remove from shortlist">★</button></td>
      <td class="px-3 py-3 font-medium text-gray-900 whitespace-nowrap">${{c.name}}</td>
      <td class="px-3 py-3 text-gray-600 max-w-xs truncate">${{c.one_liner || ''}}</td>
      <td class="px-3 py-3"><span class="inline-block px-2 py-0.5 rounded-full text-xs font-medium" style="background:${{NICHE_COLORS[c.niche_category] || '#737373'}}20;color:${{NICHE_COLORS[c.niche_category] || '#737373'}}">${{c.niche_category}}</span></td>
      <td class="px-3 py-3">${{scoreBadge(c.total_score)}}</td>
      ${{DIMS.map(d => `<td class="px-2 py-3 text-center">${{dimBadge(c[d])}}</td>`).join('')}}
    </tr>
  `).join('');

  // Remove selected ids that are no longer starred
  const starredIdSet = new Set(starred.map(c => c.id));
  for (const id of selectedIds) {{
    if (!starredIdSet.has(id)) selectedIds.delete(id);
  }}
  updateCompareBtn();
}}

function unstar(id) {{
  let ids = getShortlist().filter(x => x !== id);
  saveShortlist(ids);
  selectedIds.delete(id);
  updateBadge();
  renderShortlist();
}}

function toggleSelect(id, checked) {{
  if (checked) selectedIds.add(id);
  else selectedIds.delete(id);
  updateCompareBtn();
}}

function toggleCheckAll(checked) {{
  const ids = getShortlist();
  const starred = DATA.filter(c => ids.includes(c.id));
  if (checked) starred.forEach(c => selectedIds.add(c.id));
  else selectedIds.clear();
  renderShortlist();
}}

function selectAll() {{
  const ids = getShortlist();
  DATA.filter(c => ids.includes(c.id)).forEach(c => selectedIds.add(c.id));
  document.getElementById('checkAll').checked = true;
  renderShortlist();
}}

function deselectAll() {{
  selectedIds.clear();
  document.getElementById('checkAll').checked = false;
  renderShortlist();
}}

function compareSelected() {{
  if (selectedIds.size < 2) return;
  const comps = DATA.filter(c => selectedIds.has(c.id));
  const section = document.getElementById('compSection');
  section.classList.remove('hidden');

  // Build comparison table
  const rows = DIMS.map((d, i) => {{
    const vals = comps.map(c => c[d]);
    const best = Math.max(...vals);
    const cells = comps.map(c => {{
      const isBest = c[d] === best ? '<span class="inline-block w-2 h-2 rounded-full bg-emerald-500 ml-1"></span>' : '';
      return `<td class="px-3 py-2 text-center whitespace-nowrap">${{dimBadge(c[d])}}${{isBest}}</td>`;
    }}).join('');
    return `<tr class="border-t border-gray-100"><td class="px-3 py-2 font-medium text-gray-700 whitespace-nowrap">${{DIM_LABELS[i]}}</td>${{cells}}</tr>`;
  }});

  // Total score row
  const scoreVals = comps.map(c => c.total_score);
  const bestScore = Math.max(...scoreVals);
  const scoreCells = comps.map(c => {{
    const isBest = c.total_score === bestScore ? '<span class="inline-block w-2 h-2 rounded-full bg-emerald-500 ml-1"></span>' : '';
    return `<td class="px-3 py-2 text-center whitespace-nowrap font-semibold">${{scoreBadge(c.total_score)}}${{isBest}}</td>`;
  }}).join('');
  rows.push(`<tr class="border-t-2 border-gray-300 bg-gray-50"><td class="px-3 py-2 font-bold text-gray-900">Total Score</td>${{scoreCells}}</tr>`);

  const headerCells = comps.map(c => `<th class="px-3 py-3 font-semibold text-gray-900 text-center whitespace-nowrap">${{c.name}}</th>`).join('');
  document.getElementById('compTable').innerHTML = `
    <thead class="bg-gray-50"><tr><th class="px-3 py-3 font-semibold text-gray-600">Dimension</th>${{headerCells}}</tr></thead>
    <tbody>${{rows.join('')}}</tbody>
  `;

  // Radar chart
  if (compChart) compChart.destroy();
  const datasets = comps.map((c, i) => ({{
    label: c.name,
    data: DIMS.map(d => c[d]),
    backgroundColor: COMP_COLORS[i % COMP_COLORS.length] + '20',
    borderColor: COMP_COLORS[i % COMP_COLORS.length],
    pointBackgroundColor: COMP_COLORS[i % COMP_COLORS.length],
    pointRadius: 3,
    borderWidth: 2,
  }}));
  compChart = new Chart(document.getElementById('compRadar'), {{
    type: 'radar',
    data: {{ labels: DIM_LABELS, datasets }},
    options: {{
      scales: {{ r: {{ min: 0, max: 10, ticks: {{ stepSize: 2 }} }} }},
      plugins: {{ legend: {{ position: 'bottom' }} }}
    }}
  }});

  section.scrollIntoView({{ behavior: 'smooth' }});
}}

function closeComparison() {{
  document.getElementById('compSection').classList.add('hidden');
  if (compChart) {{ compChart.destroy(); compChart = null; }}
}}

// Initial render
renderShortlist();
</script>
"""
    html += FOOTER
    return html


# ── Main ────────────────────────────────────────────────────────────

def main():
    conn = get_connection()
    total = conn.execute("SELECT COUNT(*) FROM evaluations").fetchone()[0]
    if total == 0:
        print("No evaluations found. Run 02_evaluate.py first.")
        conn.close()
        return

    print(f"Fetching {total} evaluated companies...")
    companies = fetch_all_data(conn)
    conn.close()

    os.makedirs(OUT_DIR, exist_ok=True)

    print("Generating Data Browser (index.html)...")
    with open(os.path.join(OUT_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(generate_index(companies))

    print("Generating Analysis (analysis.html)...")
    with open(os.path.join(OUT_DIR, "analysis.html"), "w", encoding="utf-8") as f:
        f.write(generate_analysis(companies))

    print("Generating Recommendations (recommendations.html)...")
    with open(os.path.join(OUT_DIR, "recommendations.html"), "w", encoding="utf-8") as f:
        f.write(generate_recommendations(companies))

    print("Generating Shortlist (shortlist.html)...")
    with open(os.path.join(OUT_DIR, "shortlist.html"), "w", encoding="utf-8") as f:
        f.write(generate_shortlist(companies))

    print(f"\nDashboard generated in {OUT_DIR}/")
    print("Open dashboard/index.html in your browser to view.")


if __name__ == "__main__":
    main()
